export const NEWS_FETCH_DATA_SUCCESS = 'NEWS_FETCH_DATA_SUCCESS';
export const NEWS_LIKED_FETCH_SUCCESS = 'NEWS_LIKED_FETCH_SUCCESS';
export const NEWS_DISLIKED_FETCH_SUCCESS = 'NEWS_DISLIKED_FETCH_SUCCESS';

export const COLOR_ACTIVE_NEWS_LIKE = '#37003C';
export const HEIGHT_ICO_NEWS_LIKE = 36;
export const DESCRIPTION_LENGTH = 600;

export const NEWS_POPULAR_DISLIKED_FETCH_SUCCESS = 'NEWS_POPULAR_DISLIKED_FETCH_SUCCESS';
export const NEWS_POPULAR_FETCH_DATA_SUCCESS = 'NEWS_POPULAR_FETCH_DATA_SUCCESS';
export const NEWS_POPULAR_LIKED_FETCH_SUCCESS = 'NEWS_POPULAR_LIKED_FETCH_SUCCESS';